name: fi-se data load

on:
  schedule:
    - cron: '55 21 * * *'

  workflow_dispatch:

jobs:
  fi_se_load:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.14

      - name: Install dependencies
        run: |
          uv sync --frozen
          mkdir data

      - name: Load data
        run: |
          uv run python veikkaus_bot/get_data_json.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: data upload
          path: data
